server:
  port: 8900
  servlet:
    context-path: /my-springboot

spring:
  datasource:
    data: classpath:db/data.sql
    driverClassName: ''
    password: ''
    platform: h2
    schema: classpath:db/schema.sql
    url: jdbc:h2:file:./dbh2/dbc2m;AUTO_SERVER=TRUE
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
